---
title: "About this work"
author: 
date: 
output: html_document
---

The following few pages are an exploration of ways of defining a common data structure for a data frame containing all of the values within a CSR style tabular report. 

In this exploration, the functions or methods used to create such data frames are not the primary concern. If a final structure is agreed on programming of a suitable suite of robust functions to permit efficient data summarization that adhere to the structure can begin as a subsequent task.

This exploration is agnostic about the package used to create the final table reports. In the examples `htmlTable` is used, but again, if it can be demonstrated that the data structure can easily be mapped to a table, this could be replaced with any desired tabulation package, or even different packages for rendering to different output formats (html, rtf, powerpoint, etc.). The aim is to propose a structure that can be automatically mapped to a tabular (or graphical) report.


